name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Download platform artifact
      run: curl -v https://bcartifacts.blob.core.windows.net/onprem/19.0.29894.30693/platform -o platform.zip
    - name: list directory content
      run: ls
    - name: Unzip platform
      run: unzip -j -v platform.zip "ModernDev/program files/Microsoft Dynamics NAV/190/AL Development Environment/ALLanguage.vsix"
    - name: Unzip vsix
      run: unzip "ALLanguage.vsix" -d ms-dynamics-smb.al-latest
    - name: Build
      run: dotnet build --no-restore
