name: Build
on:
  push:
    branches:
      - master
      - prerelease
  pull_request:
  workflow_dispatch: null
jobs:
  setup-matrix:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create-release
        uses: release-drafter/release-drafter@v6
        if: github.event_name != 'pull_request'
        with:
          prerelease: ${{ github.ref != 'refs/heads/master' }}
          prerelease-identifier: "preview" # will create a prerelease with version number x.x.x-alpha.x
          commitish: ${{ github.ref }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
