name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Download vsix from Marketplace
      run: curl -v https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/latest/vspackage -o ms-dynamics-smb.al-latest.vsix
    - name: Unzip dependencies
      run: unzip ms-dynamics-smb.al-8.1.525271.vsix -d ms-dynamics-smb.al-latest 
    - name: Build
      run: dotnet build --no-restore
