name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: windows-latest

    steps:  
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Cache VSIX
      id: cache-vsix
      uses: actions/cache@v2
      with:
        path: ALLanguage.vsix
        key: vsix-19.0.29894.30693
    - name: Download platform artifact
      if: steps.cache-vsix.outputs.cache-hit != 'true'
      run: Invoke-WebRequest https://bcartifacts.blob.core.windows.net/onprem/19.0.29894.30693/platform -OutFile platform.zip
    - name: Unzip platform
      if: steps.cache-vsix.outputs.cache-hit != 'true'
      run: 7z x platform.zip
    - name: copy vsix
      if: steps.cache-vsix.outputs.cache-hit != 'true'
      run: cp "ModernDev\program files\Microsoft Dynamics NAV\190\AL Development Environment\ALLanguage.vsix" "./ALLanguage.vsix"
    - name: Unzip vsix
      run: unzip "ALLanguage.vsix" -d ms-dynamics-smb.al-latest
    - name: Build
      run: dotnet build --no-restore
