name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Download platform artifact
      run: curl -v https://bcartifacts.blob.core.windows.net/onprem/19.0.29894.30693/platform -o platform.zip
    - name: Unzip platform
      run: unzip (find ~+ -type f -name "*.vsix") -d ms-dynamics-smb.al-latest
    - name: Build
      run: dotnet build --no-restore
