name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Download platform artifact
      run: Invoke-WebRequest https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dynamics-smb/vsextensions/al/latest/vspackage -OutFile "ALLanguage.vsix"
    - name: Unzip vsix
      run: unzip "ALLanguage.vsix" -d ms-dynamics-smb.al-latest
    - name: Build
      run: dotnet build --no-restore
