name: Trigger build for new version
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: null

jobs:
  setup-matrix:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Get versions from Marketplace and trigger build
        shell: pwsh
        run: |
          $extensionVersions = irm -Method Post -ContentType application/json -Body '{"filters": [{"criteria": [{"filterType": 8,"value": "Microsoft.VisualStudio.Code"},{"filterType": 12,"value": "4096"},{"filterType": 7,"value": "ms-dynamics-smb.al"}],"pageNumber": 1,"pageSize": 50,"sortBy": 0,"sortOrder": 0}],"assetTypes": [],"flags": 914}' -Uri https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery?api-version=3.0-preview.1
          Write-Host "Latest version: $($extensionVersions.results[0].extensions[0].versions[0].version)"
          $latestRelease = irm https://api.github.com/repos/StefanMaron/BusinessCentral.LinterCop/releases/latest
          Write-Host "Latest release: $($latestRelease.assets.Name)"
          if ($latestRelease.assets.Name -contains "BusinessCentral.LinterCop.AL-$($extensionVersions.results[0].extensions[0].versions[0].version).dll") {
            $secureToken = ConvertTo-SecureString $env:GITHUB_TOKEN -AsPlainText
            irm -Method Post -ContentType application/json -Body '{"ref":"master"}' -Uri https://api.github.com/repos/stefanmaron/BusinessCentral.LinterCop/actions/workflows/14874791/dispatches -Authentication Bearer -Token $secureToken
            Write-Host "Build triggered"
          } else {
            Write-Host "No new version found"
          }
